export default {
  firstState: "New Call",
  loginData: {},
  activeCall: {},
  activeCallId: -1,
  activeContact: {},
  activeConv: {},
  activeVideoCall: false,
  activeTask: {},
  newCallModal: false,
  newIncomingCallModal: false,
  newMessageModal: false,
  addUserModal: false,
  profileModal: false,
  deviceSettingsModal: false,
  tasks: [],
  calls: [],
  contacts: [],
  directory: [],
  history: [],
  conversations: [],
  messages: [],
  activeNote: "",
  incomingCallModal: false,
  incomingCall: {},
  user: {},  
  activeCallRinging: false,
  activeCallInCall: false,
  activeCallOnHold: false,
  currentConv: {},
  activeCallEnded: false,
  activeCallExist: false,  
};
